# Environment JS template
cat  << EOF
window.envInject = {
    APP_ENV: "${APP_ENV?}",
    APP_VERSION: "${APP_VERSION?}",
    APP_VERSION_SHA: "${APP_VERSION_SHA?}",
    APP_VERSION_BUILD: "${APP_VERSION_BUILD?}",
    APP_HOSTNAME: "${APP_HOSTNAME?}",
    APP_FIREBASE_API_KEY: "${APP_FIREBASE_API_KEY?}",
    APP_EXAMPLE_API: "${APP_EXAMPLE_API?}",
};
EOF
