# Environment JS template
cat  << EOF
window.envInject = {
    FIREBASE_API_KEY: "${FIREBASE_API_KEY?}",
    FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN?}",
    FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID?}",
    FIREBASE_APPID: "${FIREBASE_APPID?}",
    FIREBASE_MEASUREMENT_ID: "${FIREBASE_MEASUREMENT_ID?}",
    EXAMPLE_API: "${EXAMPLE_API?}",
    VERSION_INFO__VERSION: "${VERSION_INFO__VERSION?}",
    VERSION_INFO__BUILD: "${VERSION_INFO__BUILD?}",
    APP_HOSTNAME: "${APP_HOSTNAME?}",
};
EOF
